# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${IOS_POSTGRES_PASSWORD}
      POSTGRES_USER: ${IOS_POSTGRES_USER}
      POSTGRES_DB: ${IOS_POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U ${IOS_POSTGRES_USER} -d ${IOS_POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 1s

  api:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: